#!/usr/bin/env python

"""
enforce_permissions

author: Joel Nises

todo: fix the logging
todo: add some way to specify a mask for the permissions we which to change
"""

usage = """
Usage: %prog [options] <directory>

Enforce permissions using inotify events.
"""

pripidfile = "/var/run/enforce_permissions.pid"
prilogfile = "/var/log/enforce_permissions.log"

pubpidfile = "/tmp/enforce_permissions.pid"
publogfile = "/tmp/enforce_permissions.log"

import optparse
import pyinotify
import os
import logging
import stat
import pwd
import grp
import sys
import subprocess

permissionMask = stat.S_IRWXU | stat.S_IRWXG | stat.S_IRWXO

def octalPermissionToMode(perm):
    """
    where perm is a string with three values from 0 to 7
    """

    uperm = int(perm[0])
    gperm = int(perm[1])
    operm = int(perm[2])

    return \
        (stat.S_IRUSR if uperm & 4 != 0 else 0) | \
        (stat.S_IWUSR if uperm & 2 != 0 else 0) | \
        (stat.S_IXUSR if uperm & 1 != 0 else 0) | \
        (stat.S_IRGRP if gperm & 4 != 0 else 0) | \
        (stat.S_IWGRP if gperm & 2 != 0 else 0) | \
        (stat.S_IXGRP if gperm & 1 != 0 else 0) | \
        (stat.S_IROTH if operm & 4 != 0 else 0) | \
        (stat.S_IWOTH if operm & 2 != 0 else 0) | \
        (stat.S_IXOTH if operm & 1 != 0 else 0)

def setPermissionsForFile(path, user, group, filePermissions, dirPermissions):
    s = os.stat(path)

    # First make sure we are root, or own the file. If we aren't
    # root, the requested uid needs to either be unset or the same
    # as the file
    if os.geteuid() == 0 or (s.st_uid == os.getuid() and (not user or user == s.st_uid)): 
        if user:
            if s.st_uid != user:
                logging.debug("user set for file %s" % path)
                os.chown(path, user, -1)

        if group:
            if s.st_gid != group:
                logging.debug("group set for file %s" % path)
                os.chown(path, -1, group)

        mode = s.st_mode

        if dirPermissions and filePermissions:
            if stat.S_ISDIR(mode):
                dstmode = dirPermissions
            else:
                dstmode = filePermissions

            # or in the part of the original mask that doesn't
            # involve permissions
            dstmode |= mode & ~permissionMask

            if dstmode != mode:
                logging.debug("permissions set for file %s" % path)
                os.chmod(path, dstmode)

    else:
        logging.warning("not allowed to modify the permissions of that file")

def initialEnforce(path, user, group, filePermission,
                   dirPermissions, enforceRoot = True):
    """
    walk the filesystem and set all the permissions
    """
    
    for root, dirs, files in os.walk(path):
        if enforceRoot:
            setPermissionsForFile(root, user, group, filePermissions, dirPermissions)
        else:
            for d in dirs:
                setPermissionsForFile(d, user, group, filePermissions, dirPermissions)

        for f in files:
            setPermissionsForFile(f, user, group, filePermissions, dirPermissions)

class EnforceGroupHandler(pyinotify.ProcessEvent):
    def my_init(self, user = None, group = None,
                filePermissions = None, dirPermissions = None):
        self.user = user
        self.group = group
        self.filePermissions = filePermissions
        self.dirPermissions = dirPermissions


    def process_default(self, event):
        """
        change anything that doesn't match
        """
        
        setPermissionsForFile(event.path, self.user, self.group, self.filePermissions, self.dirPermissions)
            
    
if __name__ == "__main__":
    try:
        p = optparse.OptionParser(usage = usage)
        p.add_option("-f", "--file", dest = "file_permissions", 
                     help = "The file permission to enforce", 
                     action = "store", type = "string")
        p.add_option("-d", "--directory", dest = "dir_permissions", 
                     help = "The directory permission to enforce", 
                     action = "store", type = "string")
        p.add_option("-u", "--user", dest = "user", 
                     help = "The user to enforce", 
                     action = "store", type = "string")
        p.add_option("-g", "--group", dest = "group", 
                     help = "The group to enforce", 
                     action = "store", type = "string")
        # p.add_option("-r", "--root", dest = "enforce_root",
        #              help = "If set don't enforce the permissions for the files specified on the command line, just their children"
        #              action = "store_false",)
        p.add_option("-p", "--pidfile", dest = "pidfile",
                     help = "the pidfile",
                     action = "store", type = "string")
        p.add_option("-l", "--logfile", dest = "logfile",
                     help = "the logfile",
                     action = "store", type = "string")
        
        (options, args) = p.parse_args()

        # set up the logfile
        if p.logfile:
            if os.access(p.logfile, os.W_OK):
                logfile = p.logfile
            else:
                exit("the logfile %s is not writable" % p.logfile)
        else:
            if os.access(prilogfile, os.W_OK):
                sys.stderr.write("using %s as logfile\n" % prilogfile)
                sys.stderr.flush()
                logfile = prilogfile
            elif os.access(publogfile, os.W_OK):
                sys.stderr.write("%s not writable, using %s as logfile\n" % (prilogfile, publogfile))
                sys.stderr.flush()
                logfile = publogfile
            else:
                exit("no writable locations found for logfile")

        logging.basicConfig(filename = logfile, level = logging.DEBUG)

        logging.info("Enforce watch started")

        # set up the pidfile
        if p.pidfile:
            if os.access(p.pidfile, os.W_OK):
                pidfile = p.pidfile
            else:
                errormsg = "the pidfile %s is not writable" % p.pidfile
                logging.error(errormsg)
                exit(errormsg)
        else:
            if os.access(pripidfile, os.W_OK):
                logging.debug("using %s as pidfile\n" % pripidfile)
                pidfile = pripidfile
            elif os.access(pubpidfile, os.W_OK):
                logging.debug("%s not writable, using %s as pidfile\n" % (pripidfile, pubpidfile))
                pidfile = pubpidfile
            else:
                errormsg = "no writable locations found for pidfile"
                logging.error(errormsg)
                exit(errormsg)
            

        userid = None
        groupid = None
        file_permissions = None
        dir_permissions = None

        if len(args) < 1:
            errormsg = "no files to watch"
            logging.warning(errormsg)
            exit(errormsg)

        # convert the user to uid
        try:
            if options.user:
                userid = int(options.user)
        except ValueError:
            try:
                userid = pwd.getpwnam(options.user).pw_uid
            except KeyError:
                errormsg = "there is no user named %s on this system" % options.user
                logging.error(errormsg)
                exit(errormsg)

        # make sure we are allowed to set that particular uid
        if userid and userid != os.getuid() and os.getuid() != 0:
            errormsg = "we are not allowed to change the ownership of a file to the user %s" % options.user
            logging.error(errormsg)
            exit(errormsg)

        # convert the group to gid
        try:
            if options.group:
                groupid = int(options.group)
        except ValueError:
            try:
                groupid = grp.getgrnam(options.group).gr_gid
            except KeyError:
                errormsg = "there is no group named %s on this system" % options.group
                logging.error(errormsg)
                exit(errormsg)

        # make sure the specified group is ok
        group_membership = (grp.getgrnam(x).gr_gid for x in subprocess.Popen(["groups"], stdout = subprocess.PIPE).communicate()[0].split())
        if groupid and os.getuid() != 0 and (groupid not in group_membership):
            errormsg = "we cannot change the group of the file to %s since we are not root and we are not part of the group in question" % options.group
            logging.error(errormsg)
            exit(errormsg)

        try:
            if options.file_permissions and options.dir_permissions:
                file_permissions = octalPermissionToMode(options.file_permissions)
                dir_permissions = octalPermissionToMode(options.dir_permissions)
            elif (options.file_permissions != None) != (options.dir_permissions != None):
                errormsg = "both or none of file and directory permissions must be set"
                logging.error(errormsg)
                exit(errormsg)
        except:
            errormsg = "file and directory must be on the form 755 or similar"
            logging.error(errormsg)
            exit(errormsg)

        wm = pyinotify.WatchManager()
        notifier = pyinotify.Notifier(wm, EnforceGroupHandler(user = userid,
                                                              group = groupid,
                                                              filePermissions = file_permissions,
                                                              dirPermissions = dir_permissions))

        for filename in args:
            logging.debug("enforcing initial permissions for %s" % filename)
            initialEnforce(filename, user, group, filePermissions, dirPermissions)
            
            logging.debug("adding watch for file %s"%filename)
            wm.add_watch(filename, pyinotify.IN_CREATE | pyinotify.IN_ATTRIB, rec = True, auto_add = True)

        notifier.loop(daemonize = True, 
                      pid_file = pidfile, force_kill = True,
                      stdout = logfile, stderr = logfile)

    except Exception as e:
        logging.error(e)
        raise
        
