#!/usr/bin/env python

usage = """
Usage: %prog [options] <directory>
Where permissions is in octal.
"""

pidfile = "/var/run/enforce_group.pid"
logfile = "/var/log/enforce_group.log"

import optparse
import pyinotify
import functools
import os
import logging

def enforce_group(notifier, user = None, group = None, permissions = None):
    os.
    os.chmod(notifier)

if __name__ == "__main__":
    logging.baseConfig(filename = logfile, level = logging.DEBUG)

    wm = pyinotify.WatchManager()
    notifier = pyinotify.Notifier(wm)
    wm.add_watch(directory, pyinotify.IN_CREATE | pyinotify.IN_ATTRIB, rec = True, auto_add = True)

    notifier.loop(daemonize = True, 
                  callback = functools.partial(enforce_group, 
                                               user = options.user,
                                               group = options.group,
                                               permissions = options.permissions),
                  pid_file = pidfile, force_kill = True)
